name: Send Microsoft Teams Notification

on:
  push:
    branches:
      - main
      - master
# env:
#   MS_TEAMS_WEBHOOK_URL: ${{ MS_TEAMS_WEBHOOK_URL }}

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Teams Notification
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{"text": "A new push was made to the main branch!"}' \
            $MS_TEAMS_WEBHOOK_URL