name: Send Microsoft Teams Notification

on:
  push:
    branches:
      - main
      - master
env:
  MS_TEAMS_WEBHOOK_URL: https://avaloqgroup.webhook.office.com/webhookb2/acc69694-4513-4770-9275-42f898a52f96@2ba8a4bf-3d7a-478b-b8d1-85cae49436ef/IncomingWebhook/ee99d20a71df4bb7993376f96e8a7427/9be00cee-8615-47cd-acdb-537181146f7d/V2vqRicQ0PbEBM-ImL6GUIwMByEgr2iZbJBdhuJXvNOV41
# jobs:
#   send_notification:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Send Microsoft Teams Notification
#         uses: peter-evans/teams-notify@v1
#         with:
#           webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
#           message: "A new commit was pushed to the main branch."

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Teams Notification
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{"text": "A new push was made to the main branch!"}' \
            $MS_TEAMS_WEBHOOK_URL