name: Send Microsoft Teams Notification

on:
  push:
    branches:
      - main
      - master
env:
  MS_TEAMS_WEBHOOK_URL: https://avaloqgroup.webhook.office.com/webhookb2/acc69694-4513-4770-9275-42f898a52f96@2ba8a4bf-3d7a-478b-b8d1-85cae49436ef/IncomingWebhook/ee99d20a71df4bb7993376f96e8a7427/9be00cee-8615-47cd-acdb-537181146f7d/V2vqRicQ0PbEBM-ImL6GUIwMByEgr2iZbJBdhuJXvNOV41

jobs:

  java-build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      # - name: Set up JDK 11
      #   uses: actions/setup-java@v2
      #   with:
      #     java-version: '11'
 
      # - name: Debug file structure (for troubleshooting)
      #   run: |
      #     echo "Printing the file structure..."
      #     pwd  # Print working directory
      #     ls -la  # List files to confirm HelloWorld.java exists
     
      # - name: Compile Java program
      #   run: |
      #     echo "Compiling the Java program..."
      #     javac HelloWorld.java
 
      # - name: Run Java program
      #   run: |
      #     echo "Running the Java program..."
      #     java HelloWorld
 
      - name: java
        run: echo "Hello ..."

  send_notification:
    needs: java-build
    runs-on: ubuntu-latest
    steps:
      - name: Send Teams Notification
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{"text": "repo Link: ${{ github.repository }}"}' \
            $MS_TEAMS_WEBHOOK_URL