name: Send Microsoft Teams Notification

on:
  push:
    branches:
      - main
      - master

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Microsoft Teams Notification
        uses: peter-evans/teams-notify@v1
        with:
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
          message: "A new commit was pushed to the main branch."